### ISSUE TITLE
关于第一步mix里面dirichlet分布的问题

### ISSUE THREAD

**Issue by BeechburgPieStar** [Alrash/EDM#1]
这个循环如何设置alpha=0.5的话，出现大于0.9的概率是不是太低了呀？
![image](https://github.com/user-attachments/assets/a4c9407a-d2d2-46a5-8ea4-a53ccbb58c70)

**Comment by Alrash** [comment]
实际上并没有，以实验情况来看，即使$\alpha \in [0.2, 1]$，这个情况出现概率还是十分高的。但是如果是更大的eta，比如0.98，那训练的主要时间就是在这里lmd的选择上了。通过附录的图5来看，实际上也没有必要选择更大的eta。

**Comment by BeechburgPieStar** [comment]
感谢您的回复。这边要循环很长时间，可能我是我这边源域数量太多导致的（我的源域有10个）
