### ISSUE TITLE
请教一下关于动量更新的问题？

### ISSUE THREAD

**Issue by BeechburgPieStar** [Alrash/EDM#2]
作者，您好！
      您原文里面求取的均值和方差是同一个domain所有样本的均值与方差，为什么还需要使用动量更新呢？如果数据集不变，这里面所有数据所计算出来的均值与方差不是不变吗？感觉这里的动量更新有些冗余？
![image](https://github.com/user-attachments/assets/0fb826d4-469e-4ab5-9266-b09e27344249)
![image](https://github.com/user-attachments/assets/1d1734e5-b0a1-4f02-ab97-88131f01b434)

**Comment by Alrash** [comment]
您好，是由于batch size << number of dataset的问题，这样会造成有偏采样。

**Comment by BeechburgPieStar** [comment]
感谢您的及时回复，谢谢！
